name: CorePlugin
version: ${project.version}
main: net.bapehc.core.CorePlugin
api-version: 1.13
authors: [Dawidos506, Adrianekkk, Piechuuu, Zone100054]
description: Zakaz zmiany autorow w plugin.yml :)
website: www.bapehc.pl
